export const APP_NAME = 'MK PDF Editor'
export const APP_TAGLINE = 'The all-in-one PDF editor trusted by millions worldwide.'
export const APP_VERSION = '1.0.0'
export const API_BASE_URL = import.meta.env.VITE_API_URL || ''
export const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID || ''
